on:
  push:
    branches:
      - dev
 
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout
      uses: actions/checkout@v2
 
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
 
    - name: Terraform Init
      run: terraform init

    - name: Create Output Directory
      run: mkdir -p output
 
    - name: Create Zip File
      run: zip -r output/get_books.zip src

    - name: Terraform Workspace Select
      run: terraform workspace select dev
 
    - name: Terraform Validate
      run: terraform validate
 
    - name: Terraform Apply
      run: terraform apply -auto-approve