on:
  push:
    branches:
      - dev
 
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: 'eu-central-1'
 
    steps:
    - name: Checkout
      uses: actions/checkout@v2
 
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'eu-central-1'
      
    - name: Print AWS Credentials
      run: |
        echo "AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}"
 
    - name: Terraform Init
      run: terraform init

    - name: Create Output Directory
      run: mkdir -p output
 
    - name: Create Zip File
      run: zip -r output/get_books.zip src

    - name: Create Workspace
      run: terraform workspace new dev || true
    
    - name: Select Workspace
      run: terraform workspace select dev

    - name: Create tfvars File
      run: echo "env = \"dev\"" > dev.tfvars
 
    - name: Terraform Plan
      run: terraform plan -var-file=dev.tfvars
 
    - name: Terraform Apply
      run: terraform apply -auto-approve -var-file=dev.tfvars